<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Sizes;

class SizesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Sizes::create([
            'size'=>'39',
            'quantity'=>'10',
            'idProduct'=>'1',
        ]);
        Sizes::create([
            'size'=>'40',
            'quantity'=>'10',
            'idProduct'=>'1',
        ]);
        Sizes::create([
            'size'=>'41',
            'quantity'=>'20',
            'idProduct'=>'1',
        ]);
        Sizes::create([
            'size'=>'42',
            'quantity'=>'20',
            'idProduct'=>'1',
        ]);
        Sizes::create([
            'size'=>'43',
            'quantity'=>'10',
            'idProduct'=>'1',
        ]);
        Sizes::create([
            'size'=>'44',
            'quantity'=>'20',
            'idProduct'=>'1',
        ]);
        Sizes::create([
            'size'=>'45',
            'quantity'=>'10',
            'idProduct'=>'1',
        ]);

        Sizes::create([
            'size'=>'39',
            'quantity'=>'10',
            'idProduct'=>'2',
        ]);
        Sizes::create([
            'size'=>'40',
            'quantity'=>'10',
            'idProduct'=>'2',
        ]);
        Sizes::create([
            'size'=>'41',
            'quantity'=>'20',
            'idProduct'=>'2',
        ]);
        Sizes::create([
            'size'=>'42',
            'quantity'=>'20',
            'idProduct'=>'2',
        ]);
        Sizes::create([
            'size'=>'43',
            'quantity'=>'10',
            'idProduct'=>'2',
        ]);
        Sizes::create([
            'size'=>'44',
            'quantity'=>'20',
            'idProduct'=>'2',
        ]);
        Sizes::create([
            'size'=>'45',
            'quantity'=>'10',
            'idProduct'=>'2',
        ]);

        Sizes::create([
            'size'=>'39',
            'quantity'=>'10',
            'idProduct'=>'3',
        ]);
        Sizes::create([
            'size'=>'40',
            'quantity'=>'10',
            'idProduct'=>'3',
        ]);
        Sizes::create([
            'size'=>'41',
            'quantity'=>'20',
            'idProduct'=>'3',
        ]);
        Sizes::create([
            'size'=>'42',
            'quantity'=>'20',
            'idProduct'=>'3',
        ]);
        Sizes::create([
            'size'=>'43',
            'quantity'=>'10',
            'idProduct'=>'3',
        ]);
        Sizes::create([
            'size'=>'44',
            'quantity'=>'20',
            'idProduct'=>'3',
        ]);
        Sizes::create([
            'size'=>'45',
            'quantity'=>'10',
            'idProduct'=>'3',
        ]);

        Sizes::create([
            'size'=>'39',
            'quantity'=>'10',
            'idProduct'=>'4',
        ]);
        Sizes::create([
            'size'=>'40',
            'quantity'=>'10',
            'idProduct'=>'4',
        ]);
        Sizes::create([
            'size'=>'41',
            'quantity'=>'20',
            'idProduct'=>'4',
        ]);
        Sizes::create([
            'size'=>'42',
            'quantity'=>'20',
            'idProduct'=>'4',
        ]);
        Sizes::create([
            'size'=>'43',
            'quantity'=>'10',
            'idProduct'=>'4',
        ]);
        Sizes::create([
            'size'=>'44',
            'quantity'=>'20',
            'idProduct'=>'4',
        ]);
        Sizes::create([
            'size'=>'45',
            'quantity'=>'10',
            'idProduct'=>'4',
        ]);
    }
}
